// <auto-generated />
using System;
using AnimalsLocationAPI.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimalsLocationAPI.Db.Migrations
{
    [DbContext(typeof(AnimalsLocationDbContext))]
    [Migration("20260626181956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimalsLocationAPI.Domain.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecordsFetched")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StreamId");

                    b.ToTable("IngestionRuns");
                });

            modelBuilder.Entity("AnimalsLocationAPI.Domain.IngestionStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxonId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StreamKey")
                        .IsUnique();

                    b.ToTable("IngestionStreams");
                });

            modelBuilder.Entity("AnimalsLocationAPI.Domain.IngestionWatermark", b =>
                {
                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StreamId");

                    b.HasIndex("LastRunId")
                        .IsUnique();

                    b.ToTable("IngestionWatermarks");
                });

            modelBuilder.Entity("AnimalsLocationAPI.Domain.RawObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalObservationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("StreamId");

                    b.ToTable("RawObservations");
                });

            modelBuilder.Entity("AnimalsLocationAPI.Domain.IngestionRun", b =>
                {
                    b.HasOne("AnimalsLocationAPI.Domain.IngestionStream", "Stream")
                        .WithMany("IngestionRuns")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("AnimalsLocationAPI.Domain.IngestionWatermark", b =>
                {
                    b.HasOne("AnimalsLocationAPI.Domain.IngestionRun", "LastRun")
                        .WithOne("Watermark")
                        .HasForeignKey("AnimalsLocationAPI.Domain.IngestionWatermark", "LastRunId");

                    b.HasOne("AnimalsLocationAPI.Domain.IngestionStream", "Stream")
                        .WithOne("Watermark")
                        .HasForeignKey("AnimalsLocationAPI.Domain.IngestionWatermark", "StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastRun");

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("AnimalsLocationAPI.Domain.RawObservation", b =>
                {
                    b.HasOne("AnimalsLocationAPI.Domain.IngestionRun", "Run")
                        .WithMany("RawObservations")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalsLocationAPI.Domain.IngestionStream", "Stream")
                        .WithMany("RawObservations")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("AnimalsLocationAPI.Domain.IngestionRun", b =>
                {
                    b.Navigation("RawObservations");

                    b.Navigation("Watermark");
                });

            modelBuilder.Entity("AnimalsLocationAPI.Domain.IngestionStream", b =>
                {
                    b.Navigation("IngestionRuns");

                    b.Navigation("RawObservations");

                    b.Navigation("Watermark");
                });
#pragma warning restore 612, 618
        }
    }
}
